# Generated by Django 5.1.1 on 2026-03-22 08:46

import django.db.models.deletion
import django.utils.timezone
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=tasks.models.get_default_end_date),
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.CharField(default='Unassigned', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default=tasks.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.category'),
        ),
    ]
