# Generated by Django 5.1.1 on 2026-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom_dates', 'Custom Dates')], default='once', max_length=20),
        ),
    ]
