# Generated by Django 5.1.1 on 2026-04-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
