# Generated by Django 5.1.1 on 2026-04-13 20:39

import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_custom_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(db_index=True, default=tasks.models.get_default_end_date),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'archived'], name='tasks_task_user_id_93e523_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'end_date'], name='tasks_task_user_id_3ca078_idx'),
        ),
    ]
