# Generated by Django 5.1.1 on 2026-04-01 06:12

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default=tasks.models.get_default_end_time),
        ),
    ]
