# Generated by Django 5.1.1 on 2026-04-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('weekdays', 'Select Weekdays'), ('daily', 'Everyday'), ('weekends', 'Weekends'), ('date', 'Selected Date'), ('custom', 'Custom Dates')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
